FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src/ src/
COPY worker.ts cron.ts ./
COPY prisma/ prisma/
COPY .env ./

RUN npx prisma generate
